export interface SystemRoleDefinition {
  name: string;
  permissions: string[];
}

export const protectedOwnerRoleId = "owner";

export const systemRoles: Record<string, SystemRoleDefinition> = {
  owner: {
    name: "Owner",
    permissions: [
      "members.read",
      "members.manage",
      "roles.read",
      "roles.manage",
      "owners.read",
      "owners.create",
      "owners.update",
      "owners.archive",
      "transactions.read",
      "transactions.create",
      "transactions.update",
      "transactions.archive",
      "transfers.read",
      "transfers.create",
      "transfers.correct",
      "transfers.archive",
      "debts.read",
      "debts.create",
      "debts.update",
      "debts.archive",
      "receivables.read",
      "receivables.create",
      "receivables.update",
      "receivables.archive",
      "assets.read",
      "assets.create",
      "assets.update",
      "assets.archive",
      "reports.read",
      "activity.read",
      "business.settings",
    ],
  },
  admin: {
    name: "Admin",
    permissions: [
      "members.read",
      "roles.read",
      "owners.read",
      "owners.create",
      "owners.update",
      "owners.archive",
      "transactions.read",
      "transactions.create",
      "transactions.update",
      "transactions.archive",
      "transfers.read",
      "transfers.create",
      "transfers.correct",
      "transfers.archive",
      "debts.read",
      "debts.create",
      "debts.update",
      "debts.archive",
      "receivables.read",
      "receivables.create",
      "receivables.update",
      "receivables.archive",
      "assets.read",
      "assets.create",
      "assets.update",
      "assets.archive",
      "reports.read",
      "activity.read",
      "business.settings",
    ],
  },
  accountant: {
    name: "Accountant",
    permissions: [
      "owners.read",
      "transactions.read",
      "transactions.create",
      "transactions.update",
      "transfers.read",
      "transfers.create",
      "debts.read",
      "debts.create",
      "debts.update",
      "receivables.read",
      "receivables.create",
      "receivables.update",
      "assets.read",
      "reports.read",
      "activity.read",
    ],
  },
  viewer: {
    name: "Viewer",
    permissions: [
      "members.read",
      "owners.read",
      "transactions.read",
      "transfers.read",
      "debts.read",
      "receivables.read",
      "assets.read",
      "reports.read",
    ],
  },
};
