// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmHz1Ys-fzYjlvvLgUDBVTpqQVA8tS-d4',
    appId: '1:339362530098:web:382a1f8889f4602baf0d2b',
    messagingSenderId: '339362530098',
    projectId: 'money-manager-2df2b',
    authDomain: 'money-manager-2df2b.firebaseapp.com',
    storageBucket: 'money-manager-2df2b.firebasestorage.app',
    measurementId: 'G-9SX1YNSE3W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAv0EluD5ITPvX6IYKr56oMDzD_idk3-Uo',
    appId: '1:339362530098:android:16c4c0aec58cc934af0d2b',
    messagingSenderId: '339362530098',
    projectId: 'money-manager-2df2b',
    storageBucket: 'money-manager-2df2b.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDO6vFLQ_QRJ5VjgQ0bHr9LYZpZUl9TIW4',
    appId: '1:339362530098:ios:31ea243b0adf98afaf0d2b',
    messagingSenderId: '339362530098',
    projectId: 'money-manager-2df2b',
    storageBucket: 'money-manager-2df2b.firebasestorage.app',
    iosBundleId: 'com.example.moneyManager',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDO6vFLQ_QRJ5VjgQ0bHr9LYZpZUl9TIW4',
    appId: '1:339362530098:ios:31ea243b0adf98afaf0d2b',
    messagingSenderId: '339362530098',
    projectId: 'money-manager-2df2b',
    storageBucket: 'money-manager-2df2b.firebasestorage.app',
    iosBundleId: 'com.example.moneyManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmHz1Ys-fzYjlvvLgUDBVTpqQVA8tS-d4',
    appId: '1:339362530098:web:5a5403fd25803901af0d2b',
    messagingSenderId: '339362530098',
    projectId: 'money-manager-2df2b',
    authDomain: 'money-manager-2df2b.firebaseapp.com',
    storageBucket: 'money-manager-2df2b.firebasestorage.app',
    measurementId: 'G-JMZ40SGLP8',
  );
}
