// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9RlGnIvTjm2wdOSb3gixCiM4JMdlpkiw',
    appId: '1:651605242767:web:305c2475bc95a8d04951fa',
    messagingSenderId: '651605242767',
    projectId: 'moneymaneger-v2',
    authDomain: 'moneymaneger-v2.firebaseapp.com',
    storageBucket: 'moneymaneger-v2.firebasestorage.app',
    measurementId: 'G-CZDR8DG15H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCv98YqPUwDnOyJhriXrZJW9W3faH77CKE',
    appId: '1:651605242767:android:0b07b5d8e2f7ca694951fa',
    messagingSenderId: '651605242767',
    projectId: 'moneymaneger-v2',
    storageBucket: 'moneymaneger-v2.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0dMFwgx1gffxibFV7wGYLft9yYhpOnWc',
    appId: '1:651605242767:ios:d9fd21dcdd7fb3984951fa',
    messagingSenderId: '651605242767',
    projectId: 'moneymaneger-v2',
    storageBucket: 'moneymaneger-v2.firebasestorage.app',
    iosBundleId: 'com.example.moneyManager',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0dMFwgx1gffxibFV7wGYLft9yYhpOnWc',
    appId: '1:651605242767:ios:d9fd21dcdd7fb3984951fa',
    messagingSenderId: '651605242767',
    projectId: 'moneymaneger-v2',
    storageBucket: 'moneymaneger-v2.firebasestorage.app',
    iosBundleId: 'com.example.moneyManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9RlGnIvTjm2wdOSb3gixCiM4JMdlpkiw',
    appId: '1:651605242767:web:fca02dad9cf783974951fa',
    messagingSenderId: '651605242767',
    projectId: 'moneymaneger-v2',
    authDomain: 'moneymaneger-v2.firebaseapp.com',
    storageBucket: 'moneymaneger-v2.firebasestorage.app',
    measurementId: 'G-L88N1VHLSR',
  );
}
